### ISSUE TITLE
Relation "wiki_0" does not exist

### ISSUE THREAD

**Issue by psychemedia** [turbot/steampipe-plugin-html#3]
Trying the demo from the README, the initial query works fine, and the CSV file appears to be downloaded to the correct path, but the second query returns `Error: relation "wiki_0" does not exist (SQLSTATE 42P01)`.

I am new to `steampipe` - is there another setting required somewhere that also sets the CSV path for use in arbitrary queries?

**Comment by bigdatasourav** [comment]
Hey @psychemedia, I apologize for the delay in responding and for the inconvenience you’re experiencing.

The development of the plugin is on hold due to other higher-priority tasks. However, we will return to it shortly.
